import React, { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { FileText, Calendar } from 'lucide-react';

export default function Loans() {
  const { customerId } = useAuth();
  const [loans, setLoans] = useState<any[]>([]);
  const [schedules, setSchedules] = useState<any[]>([]);

  // Loan Application Form
  const [amount, setAmount] = useState('');
  const [tenure, setTenure] = useState('');
  const [type, setType] = useState('Personal');

  async function loadData() {
    const { data: lnData } = await supabase.from('loan').select('*').eq('customer_id', customerId);
    if (lnData) {
      setLoans(lnData);
      
      const loanIds = lnData.map(l => l.loan_id);
      if (loanIds.length > 0) {
        const { data: schedData } = await supabase
          .from('repayment_schedule')
          .select('*')
          .in('loan_id', loanIds)
          .order('due_date', { ascending: true });
        
        if (schedData) setSchedules(schedData);
      }
    }
  }

  useEffect(() => { loadData(); }, [customerId]);

  const handleApply = async (e: React.FormEvent) => {
    e.preventDefault();
    await supabase.from('loan').insert([{
      customer_id: customerId,
      principal_amount: parseFloat(amount),
      interest_rate: type === 'Home' ? 8.5 : 12.5, // Dummy default rates
      tenure_months: parseInt(tenure),
      loan_type: type
    }]);
    
    setAmount(''); setTenure(''); setType('Personal');
    loadData();
  };

  return (
    <>
      <div className="page-header">
        <div>
          <h1 className="text-gradient">Loan Services</h1>
          <p style={{ color: 'var(--text-muted)' }}>Apply for new loans and view your EMI schedules. Schedule is auto-generated by the database upon approval.</p>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'minmax(300px, 1fr) 2fr', gap: '24px' }}>
        <div className="glass-panel" style={{ alignSelf: 'start', position: 'sticky', top: '24px' }}>
          <h3>Apply for Loan</h3>
          <form onSubmit={handleApply} style={{ marginTop: '16px' }}>
            <div className="form-group">
              <label>Loan Type</label>
              <select className="form-control" value={type} onChange={e => setType(e.target.value)}>
                <option value="Personal">Personal Loan (12.5%)</option>
                <option value="Home">Home Loan (8.5%)</option>
                <option value="Auto">Auto Loan (9.5%)</option>
              </select>
            </div>
            
            <div className="form-group">
              <label>Amount requested (₹)</label>
              <input type="number" min="10000" className="form-control" placeholder="500000" value={amount} onChange={e => setAmount(e.target.value)} required />
            </div>

            <div className="form-group">
              <label>Tenure (Months)</label>
              <input type="number" min="6" max="360" className="form-control" placeholder="60" value={tenure} onChange={e => setTenure(e.target.value)} required />
            </div>

            <button type="submit" className="btn-primary" style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>
              <FileText size={16} /> Submit Application
            </button>
          </form>
        </div>

        <div>
          {loans.map(loan => (
            <div key={loan.loan_id} className="glass-panel" style={{ marginBottom: '20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid var(--border-light)', paddingBottom: '12px', marginBottom: '16px' }}>
                <div style={{ display: 'flex', flexDirection: 'column' }}>
                  <h4 style={{ fontSize: '1.2rem' }}>{loan.loan_type} Loan</h4>
                  <span style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>{loan.tenure_months} months @ {loan.interest_rate}% p.a.</span>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <span className={`badge ${loan.status === 'Approved' ? 'success' : loan.status === 'Pending' ? 'warning' : 'danger'}`}>
                    {loan.status}
                  </span>
                  <div style={{ marginTop: '8px', fontSize: '1.2rem', fontWeight: 600, color: 'var(--accent-gold)' }}>
                    ₹ {Number(loan.principal_amount).toLocaleString('en-IN')}
                  </div>
                </div>
              </div>

              {schedules.filter(s => s.loan_id === loan.loan_id).length > 0 ? (
                <div>
                  <h5 style={{ marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' }}><Calendar size={14} /> EMI Schedule</h5>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: '12px' }}>
                    {schedules.filter(s => s.loan_id === loan.loan_id).map((sch, i) => (
                      <div key={sch.schedule_id} style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '8px', border: '1px solid var(--border-light)' }}>
                        <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>M-{i+1}: {sch.due_date}</div>
                        <div style={{ fontWeight: 600, marginTop: '4px' }}>₹ {Number(sch.emi_amount).toFixed(0)}</div>
                        <div style={{ fontSize: '0.75rem', color: sch.pay_status === 'Paid' ? 'var(--success)' : 'var(--warning)', marginTop: '4px', textTransform: 'uppercase' }}>{sch.pay_status}</div>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                  {loan.status === 'Pending' ? 'EMI Schedule will be generated upon admin approval.' : 'No schedule generated.'}
                </p>
              )}
            </div>
          ))}

          {loans.length === 0 && (
            <div className="glass-panel" style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>
              No active or past loans found.
            </div>
          )}
        </div>
      </div>
    </>
  );
}
